### PR TITLE
Update ballot election period documentation

### PR DESCRIPTION
**Pull request by sethtrain**
@3dna/autobots @codealchemy

### CODE REVIEW

**Comment by codealchemy** [comment]
One comment, otherwise LGTM :cool:

**Comment by sethtrain** [comment]
Ok, cool.  I went ahead and added a note just to be sure.

**Comment by codealchemy** [comment]
:+1:

**Comment by kaip** [comment]
:+1:

**Comment by correlator** [comment]
:+1:

**Pull request merged**
