### PR TITLE
Add nested ballot resources to people api docs

### PR DESCRIPTION
**Pull request by kaip**
@3dna/autobots @codealchemy 

Do I need to add anything other than ballots to the person resource?

### CODE REVIEW

**Comment by codealchemy** [comment]
@kaip a few questions/notes:

- Is the `election_period` case sensitive?
- I believe the political parties are localized, per our docs [here](http://nationbuilder.com/political_party_codes)
- For non-US ballots, is `state` a required attribute?

Outside of that this looks good to me!

**Comment by kaip** [comment]
@codealchemy Election period is not case sensitive.  The political parties are localized in general, but not for this endpoint because most international parties will not have multiple party's primary ballots.  State is currently required but it should not be for international nations (I'll indicate that in the docs): https://trello.com/c/UHIFM0mw/1048-do-not-require-state-for-international-ballots

**Comment by kaip** [comment]
@codealchemy Never mind, the parties are based on the nation's origin as you said

**Comment by codealchemy** [comment]
@kaip cool thanks :+1: :ship:

**Pull request merged**
